### ISSUE TITLE
KMS requirement for SLSA 3/4 is too prescriptive

### ISSUE THREAD

**Issue by mattmoor** [slsa-framework/slsa#187]
This is the wording in particular that I'm looking at:
> The provenance signing key MUST be stored in a secure key management system accessible only to the build service account.

In particular, this precludes models that take advantage of ephemeral keys and CAs (e.g. Sigstore's Fulcio), which are not KMS systems.  However, I'd argue that despite something like Fulcio *not* satisfying this as-written, it is a strictly stronger model because long-lived key material is never exposed to the build service.

As a sort of meta-comment, SLSA doesn't really touch on the exclusive use of [very] short-lived credentials, despite the fact that exfiltrating long-lived creds is a key attack vector.  I was mentioning to @kimsterv that the use of exclusively short-lived credentials (e.g. Workload Identity) and keys (e.g. Fulcio) might make a nice basis for SLSA 5.

**Comment by dlorenc** [comment]
I think the language around all of the signing stuff needs to be improved a bit. Key management is only one part of the puzzle, without rotation/revocation you're really not left in a much better place than not signing things at all.

**Comment by trishankatdatadog** [comment]
Mark: I think a bit of both: generalize the description to include both use cases, and also list some concrete options.

**Comment by kimsterv** [comment]
@trishankatdatadog flagging that this issue ties into the [doc](https://docs.google.com/document/d/1z_9C13hvGFcBx3l7ehvXmiCcU5Ywf8KROPDia7Nhymw/edit?usp=sharing) discussed today in the wg

**Comment by awwad** [comment]
Current text:
> This SHOULD be through a digital signature from a private key accessible only to the service generating the provenance.

' nice to know this has been highlighted before.  ^_^

Preston and I happened to stumble over this requirement and brought it up this week because the existing text is vague enough to reasonably be seen _not_ to fit very _good_ implementations and also to reasonably be seen to fit very _bad_ implementations.

Access to a private key can be seen as meaning visibility of the raw key value (exfiltration risk) or ability to use the key during compromise (use risk).  It's easy to think of this as a requirement for reducing the odds of key exfiltration, but I think it would be best to make this about key access in the broad sense of ability to use the key.

**Comment by shaunmlowry** [comment]
related https://github.com/slsa-framework/slsa/issues/414
