### ISSUE TITLE
Indicate platform vs project configuration in requirements

### ISSUE THREAD

**Issue by mattmoor** [slsa-framework/slsa#188]
I agree with the principle that the definition of builds should be versioned through version control.

However, my concern with the current wording (esp. at SLSA 4) is that I do NOT believe that changes to these definitions should be validated by the changed bits themselves.  We want untrusted user code to be validated by trusted user code, and if a build definition is used to validate itself, then it violates this simple induction.

A good example of the reflection of this trust is the distinction between [`pull_request`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request) and [`pull_request_target`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target) in Github Actions.  The former is NOT trusted, and so it doesn't get access to things like secrets.  The latter is trusted (it has been reviewed and merged), and can access secrets and read/write the repo.

**Comment by MarkLodato** [comment]
Oh, I think I understand now. Let's take a look at https://github.com/yaml/pyyaml/actions/workflows/ci.yaml as an example. There, the CI workflow can be invoked in two ways:

- after submission (`push`)
- before submission with a pending change (`pull_request`)

In the `push` case, we trust the build configuration because it has been reviewed and submitted. (I believe this is not in question?)

But in the `pull_request` case, you are asking whether the build configuration comes from the submitted configuration or the pending change or both? Is the concern (a) that untrusted code may get access to secrets available to the workflow, or (b) that the source it's building from is not submitted so it should not be trusted?

For (a), the build should not have access to sensitive secrets. At SLSA 3, we require [isolated builds](https://slsa.dev/requirements#isolated) and the provenance secrets to be unavailable to the "build as code" controlled component ([non-falsifiable](https://slsa.dev/requirements#non-falsifiable)). It shouldn't matter that some untrusted branch can be built using the same workflow, since each build is properly isolated from one another.

For (b), the provenance records what sources it read the build config from, and the trust is established based on that source location. In other words, a policy would only accept builds from a particular source. Looking at the pyyaml example, the policy would allow a build from [`yaml/pyyaml@release/6.0`](https://github.com/yaml/pyyaml/actions/runs/1338927218) but not [`hugovk/pyyaml@test-3.10-final`](https://github.com/yaml/pyyaml/actions/runs/1358829841), even though both were built using the same GHA workflow.

Does that help?

(All this should be better explained in the docs, but I wanted to first see if I properly understand your question.)

**Comment by mattmoor** [comment]
> Is the concern ...

The concern is more along the lines of: it is participating in its own validation.  If the build itself is "code", how is that user-sourced "code" sandboxed and vetted before it is trusted.  A human must review it is one answer to this.

> the build should not have access to sensitive secrets. At SLSA 3, we require isolated builds and the provenance secrets to be unavailable to the "build as code" controlled component

It seems somewhat implicit in this that SLSA 3 is not achieved through the "build as code" itself[1], otherwise I could strip these protections (knowingly or not), unless/until it is caught by a human reviewer.

[1] - or that the "build as code" is configured through a separate repository from the code pursuing SLSA 3, or even that the "build as code" is not activated until a human reviewer has manually reviewed (and likely merged) it.


> Does that help?

Yes and no.  I think it would be helpful to enrich each of the line items with more comprehensive intent, so that these things aren't leaning on each other in nuanced ways.  I think some users might think themselves closer to SLSA X than they are if they are simply missing a single checkbox, when they may be violating the spirit of several other items that don't have full effect without that one checkbox.  We talked about something similar in (IIRC) the CNCF TAG for supply chain where it would be useful to understand what folks give up by not adopting particular aspects of the reference architecture, since something like SLSA 3 is (to be cliche) "greater then the sum of its parts".

**Comment by marcelamelara** [comment]
+1 to resolving this during v1.0. Clearly identifying who is responsible for meeting a requirement should be part of the discussion on the set of v1.0 requirements, and which SLSA level a given requirement should map to.

**Comment by MarkLodato** [comment]
Marking this as complete since #536 was merged. More improvements are possible, but I think we achieved the main gist of this issue. If you disagree, please comment.
