### ISSUE TITLE
Code review exemption for changes by trusted robots?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#196]
For the [two-person reviewed](https://slsa.dev/requirements#two-person-reviewed) requirement at SLSA 4, how should we handle changes authored by robots? It's always an option for two trusted persons to review and approve, but what if we want the changes to be completely automated or to only require a single reviewer? Should there be some exemption in the case that the trusted robot is locked down and honors the two-person principle?

**Comment by Hixie** [comment]
One example of a robot we use in Flutter land is the autoroll bot for rolling one of our repositories into another one of our repositories. We use the same rules for contribution to both repositories and to the bot itself, but it would be impractical to also require those rules for the bot's actions, since the bot is continually rolling (one commit every 3 hours, on average).

**Comment by justinabrahms** [comment]
Another example of one of these robots is my company has several teams which use a robo-committer to bump versions in their pom.xml files on commit.

**Comment by zachariahcox** [comment]
I believe the current thinking is that SLSA is concerned with tamper-resistant provenance attestations. 
EG: It is up to more opinionated "VSA"-type tooling to decide whether or not robots are allowed. 
At the very least, we expect the "evidence" and the claims summarized by that evidence to be issued by different actors.
