### ISSUE TITLE
Unclear requirement around build service secrets

### ISSUE THREAD

**Issue by james-w** [slsa-framework/slsa#228]
> - It MUST NOT be possible for a build to access any secrets of the build service, such as the provenance signing key.

I am not sure what this means, and I asked some of the people on our team, and we got a few different
answers, with no-one confident that they had the right answer.

What would be other examples of secrets that should be restricted under this?

It says that no secrets should be accessible for the build, but how would you deal with things like:
* Connecting to a sonarqube instance to get code analysis
* Fetching dependencies from private storage
* Pushing built artifacts to private storage

Perhaps it's about what is defined as the build in this statement?

**Comment by mlieberman85** [comment]
@MarkLodato I by and large agree.

@james-w A bit of extra elaboration:

The premise of this requirement is  that the build service itself is easier to reason about than a user defined build that could run any arbitrary action, including printing out of secrets. Also since build actions can call out to compilers and other build tools which themselves are hard to reason about it is much easier for secrets to leak as a result of a secret in a build itself as opposed to a hardened build service.

This framework doesn't get into best practices, but should link to them in the future. From a best practices perspective:
* If possible have the build service delegate temporary access to the individual builds rather than giving builds themselves the secrets.
* When that isn't possible try and use build tasks specifically developed for a single purpose, e.g.  sonarqube as opposed arbitrary shell commands that use sonarqube cli tool or something like that.

**Comment by james-w** [comment]
Thanks for the clarification, I think that it makes it clearer. This matches what some of us thought, but others saw this requirement and thought that it would require us to try and run builds that used no secrets in order to comply.

I think that trying to include some of this clarification in to the framework would be useful.
