### ISSUE TITLE
Donate SLSA 3 github workflows to slsa-framework or ossf

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa#331]
Hey everyone!

Laurent @laurentsimon and I presented about a reusable workflow + OIDC-based signing to achieve SLSA 3 in GitHub Actions at the last SLSA bi-weekly. We were hoping to migrate or donate our workflows to a larger organization than gossts, and were wondering if the slsa community or ossf organization would be able to host these. I would be happy to maintain the code here, and add documentation and specification. We anticipate migrating in the short-term:

1. A provenance only reusable workflow (build/ecosystem agnostic): `.github/workflows/slsa3_provenance.yml` @MarkLodato 
2. A golang implementation: `.github/workflows/slsa3_go.yml`.
3. A generic provenance verifier that trusts the two workflows above. 

I would love to migrate (1) under the slsa-framework organization: It's build and ecosystem agnostic, and has a very easy adoption story. It does require some library code, and would also require a README.md and a technical specification/documentation, so a full repository makes sense here. 

On the other hand, perhaps the golang implementation and other ecosystem specific projects should live under the umbrella of ossf or a community repository. Do you have any suggestions? 

Finally, the provenance verifier (github-provenance-verifier?) is build agnostic, and we would love to build this out into a larger tool that can specifically verify provenance generated from reusable workflows using GitHub workflow identities. 

Would love any comments, or feedbacks, or better names!

cc @laurentsimon

**Comment by inferno-chromium** [comment]
Since this is an implementation of SLSA, it would fit very well in a repo under slsa-framework org (like slsa-examples or something).

**Comment by marcofranssen** [comment]
I have started a similar initiative.

https://github.com/marcofranssen/slsa-workflow-examples

Utilizing:

- https://github.com/philips-labs/slsa-provenance-action
- https://github.com/sigstore/cosign
- https://github.com/anchore/syft

Also see my blog about this example:
https://marcofranssen.nl/secure-your-software-supply-chain-using-sigstore-and-github-actions

**Comment by MarkLodato** [comment]
@laurentsimon I don't see why not. I think we can just do it now unless @slsa-framework/slsa-steering-committee disagrees.

I suggest that we move the repo to the slsa-framework project, with warning at the top of the README saying it's not yet official. If anyone objects within a week or so, we just move it back. Assuming everyone is OK with it, we remove the warning right before we do an official tagged release. What do you think?

One repo per workflow sounds good to me.

By the way, regarding pinning, we probably want to recommend only pinning to tagged releases, not arbitrary commits. This way we minimize the number of supported "builder IDs" we have to track.

**Comment by laurentsimon** [comment]
> @laurentsimon I don't see why not. I think we can just do it now unless @slsa-framework/slsa-steering-committee disagrees.

+1

> I suggest that we move the repo to the slsa-framework project, with warning at the top of the README saying it's not yet official. If anyone objects within a week or so, we just move it back. Assuming everyone is OK with it, we remove the warning right before we do an official tagged release. What do you think?

+1

> One repo per workflow sounds good to me.

+1

> By the way, regarding pinning, we probably want to recommend only pinning to tagged releases, not arbitrary commits. This way we minimize the number of supported "builder IDs" we have to track.

We could get around this by having `builderID` be the generic `.github/workflows/slsa/workflow.yml` and the `materials` contain the hash/tag of it. Starting with tag simplifies things , so I think it's a good idea

**Comment by trishankatdatadog** [comment]
> @laurentsimon I don't see why not. I think we can just do it now unless @slsa-framework/slsa-steering-committee disagrees.

Let's do it

**Comment by asraa** [comment]
> @marcofranssen Nice! I hadn't seen that. Let's start a separate issue to figure out how to incorporate that, leaving this issue just about the gosst one?

+1 -- Marco, maybe also we could colab on some of them and incorporate some of the upload, SBOM work? One major difference we have is the non-falsifiable piece from guaranteeing maintainer isolation w the reusable workflow. We could colab on one of these repos!

**Comment by laurentsimon** [comment]
@asraa and I have brainstormed offline and these are the repos we think we'd like to have created to host the code:

1. `github-generator`: will host code to generate provenance (including reusable workflows), e.g. `.github/workflows/slsa3_provenance.yml` that generate provenance and is ecosystem-agnostic. 

2. `github-generator-go`: will host code to build and generate provenance for projects written in `go`. In the long-term, it will use some generic code from `github-generator`. This repo will also host various reusable workflows specific to `go` projects, such as `.github/workflows/slsa3_builder_provenance.yml`, `.github/workflows/slsa4_builder_provenance.yml`, `.github/workflows/slsa3_provenance.yml`, etc. Later we can create `github-generator-rust`, etc.
 
3. `github-verifier`: will host generic code about verifying the provenance generated on GitHub, and can be used by any ecosystems.

Wdut?

**Comment by joshuagl** [comment]
This is amazing. Thanks you @asraa and @laurentsimon for volunteering to maintain this as part of slsa-framework. With my steering committee hat on, I'd love to have these repos be part of the slsa-framework org.

I'm really interested in playing around with the code and working on some generators for other ecosystems (initially I'm thinking of Maven/Java and Python). 

If you're looking for co-maintainers (especially on `github-generator` and `github-verifier`) I'd be happy to volunteer. Perhaps @marcofranssen too?

**Comment by MarkLodato** [comment]
@laurentsimon @asraa Sounds good, with a few questions:

* Should we prefix each with `slsa-` so that it looks OK in forks? I'm fine either way.
* Do you want to transfer the existing repo (along with Github issues, etc) or do you want me to create a fresh one that you push into? If the former, you initiate that via the [settings page](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository). If the latter, I'll initiate.
* For the verifier, my inclination would be to create a single verification system that is not builder specific, so we'd want to name it accordingly.

**Comment by laurentsimon** [comment]
@joshuagl Would gladly have you be a maintainer, thanks!

@marcofranssen it'd be great to have you come onboard too! I think your examples deal with containers, and they are a big piece we need to work out so your help would be invaluable. For example, it's not clear to me how provenances are composed and are captured from a package (pip, npm, etc) into the final container: does the container provenance contain nested provenance for each dependency? Do we refer to them via "reference" (maybe implicit in the SBOM/material field of the provenance) and leave the burden of fetching each dependency's provenance to the consumer? Or something else (out of scope)? 
Other questions include: in the simple case of a go binary, how do we capture the command used to compile it? Do we parse each dockerfile's command? Do we use a 2-step process where the binary is first compiled using our workflows and then included in the final container via a curl or something? Or do we turn to things like https://github.com/google/ko and https://buildah.io/? Or is this out of scope?

> @laurentsimon @asraa Sounds good, with a few questions:
> 
> * Should we prefix each with `slsa-` so that it looks OK in forks? I'm fine either way.

no strong opinion from me. If anyone has an opinion, please chime in

> * Do you want to transfer the existing repo (along with Github issues, etc) or do you want me to create a fresh one that you push into? If the former, you initiate that via the [settings page](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository). If the latter, I'll initiate.

Transferring is probably easier, we'll just need to rename the repos. @asraa any objections?

> * For the verifier, my inclination would be to create a single verification system that is not builder specific, so we'd want to name it accordingly.

Do you mean a repo called `verifier` instead of `github-verifier`? I suppose we could start with the latter and later on create a generic `verifier` repo that uses the APIs exposed by individual  `<ecosystem>-verifier` if we needed to? But I don't have a strong opinion on this, maybe we could start right away with the generic `verifier`... If anyone has an opinion, please chime in. @asraa any thoughts?

**Comment by laurentsimon** [comment]
so the transfer can only be done if the repo owner have push access to `slsa-framework`. The repo owner is `gossts` so I think I need this use to be a collaborator temporarily to do the transfer. This way we'd keep issues, history, etc

Let me know f this is feasible. Thanks!

**Comment by laurentsimon** [comment]
Yes, closing.
