### ISSUE TITLE
Link to verification_summary/v0.1

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#334]
https://slsa.dev/verification_summary/v0.1 exists now but you can't navigate to it from the rest of the site.

Perhaps we should turn the 'Provenance' menu at the top into a drop down to link to various things?

E.g.

* Attestations
  * Provenance
  * Verification Summary

If we really like having 'Provenance' directly in the top menu then we could do:

* Specifications
  * ...
  * Attestations (new page that links to all the defined attestations including provenance?)

WDYT @MarkLodato you seem to be the most involved in the website look & feel?

**Comment by MarkLodato** [comment]
Yup.  "Attestations" menu sounds good. Also I'd rename "Specifications" to "Levels" (and "Levels" to "Security levels") since the former is ambiguous. That is:

* **Levels** [was "Specifications"]
  * Introduction
  * Terminology
  * **Security Levels** [was "Levels"]
  * ...
* **Attestations**
  * Provenance
  * **Verification summary**

I put together a draft at #336 but as you can see our website doesn't support multiple things at the moment. We should create a new issue for that.
