### ISSUE TITLE
Add a SLSA 3.5 omitting 2-person control (non-unilateral)

### ISSUE THREAD

**Issue by david-a-wheeler** [slsa-framework/slsa#4]
Many (possibly most) OSS projects are single-person. Yes, it'd be awesome if they had multiple people, but for a variety of reasons they don't. If those with multiple people would be hard-pressed to *always* have changes reviewed by a second person.

It is obviously *much* better if a project has 2-person control (non-unilateral), but since that will often not be possible, we should have a level that expresses what we *can* get in that case.

I think it'd be good to have at least one level between SLSA 2 and 3, call it 2.5, that adds hermiticity without non-unilateral (2-person control). That way, you get what you *can* get out of a smaller project.

**Comment by MarkLodato** [comment]
I fully support adding more intermediate levels. (But let's use integers - nothing depends on the current numbering!)

In addition to splitting out "two-person review", we might also want to have a separate intermediate level for "policy that lists the specific top-level sources". (This requirement isn't spelled out in the doc, but it is important.) The latter is actually quite difficult at large organizations because it cannot be done centrally. Instead, each resource must have a custom policy listing which sources are expected _for that resource_. Hermeticity and two-party review don't have that problem - you can create a _generic_ policy saying "must use a hermetic build system" and "must be two-person reviewed."

[At Google](https://cloud.google.com/security/binary-authorization-for-borg), for example, we were able to enforce two-person review by default with a generic policy that we flipped on centrally, without contacting individual teams. But that only got us to SLSA 2. Getting to SLSA 3 required having every team specify what sources they expected, and that was much more expensive. Personally I wished we had made the policy bit a separate level.

All this is to say, it's not obvious to me whether "2-person control" or the policy bit should come first. :-)

**Comment by TomHennen** [comment]
I'm not against adding levels, but before we do, should we agree on what the level definitions are _for_?

Are they for:

1. Being able to distinguish between each _incremental_ improvement in the security posture of the supply chain?
1. Being able to distinguish between each _significant_ improvement in the security posture of the supply chain?
1. Something else? 

(I don't think that list actually captures all the potential use cases.)

I'd argue that we probably don't want to have a different level for each improvement that could be made. e.g. having one level for builds that are isolated and another level for builds that provide source integrity (both of which are currently listed as L2).  For one thing it can be hard to provide an _ordering_ of which is better than the other.  For another, we could overwhelm users who are trying to understand what each level is 'for'.

Regarding 'significant' in 2 above, is having a policy that lists top-level sources 'significant' if the source itself doesn't require two-party review?  A malicious actor would only have to compromise one account to change what the top-level source allowed by policy does.  That might suggest an ordering, i.e. it _would_ be significant to require top-level source if two-party review is already required, but it _would not_ be significant to require top-level source if two-party review isn't required.

From that point of view, when is requiring hermeticity 'significant'?  Or could it just be rolled into some other level that is already providing significant value.  If we had a separate level for just hermeticity builders could certainly use it to show progress, but then they could also show progress just by being able to check the box, even if they're not ready for the next level.

**Comment by MarkLodato** [comment]
Perhaps we should drop two-party review at SLSA 3 and leave it to some future SLSA 4. The two-party principle would still hold for the *platform* (build, source, deploy, etc.) but not for the actual source code. In other words, it would take two colluding individuals to falsify the provenance, but only one individual to make source code changes.

Two main arguments in favor of this proposal:

- Based on the experience of [CII Best Practices](https://bestpractices.coreinfrastructure.org/en), almost no one is willing to commit to **mandatory** two-party review for **all** changes, save for a handful of companies like Google. Thus, if no one ever reaches a level in practice, the level is not very useful.
- The other SLSA 3 build requirements (hermeticity and reproducibility) are a one-time cost, whereas code review is an ongoing burden.

**Comment by MarkLodato** [comment]
Deferring to v1.1+ since this is about source requirements, which are not being defined in v1.0.

**Comment by zachariahcox** [comment]
I think there will be code quality benefits to multi-person code review, just as there will be from thorough unit test coverage. I'd propose we just record "who reviewed what" and attach it as a "claim" to the revision. 

If the consumer cares about that (or any) specific security claim, they can count the number of discrete reviewers during their revision verification process.

**Comment by zachariahcox** [comment]
Marking "closed" for now! Please feel free to reopen if you feel we didn't address this topic fully 👍
