### ISSUE TITLE
Some folks reporting that slack link on slsa.dev requires an LF login

### ISSUE THREAD

**Issue by mlieberman85** [slsa-framework/slsa#499]
Some people, for example in the mailing list have reported that the slack link on: https://slsa.dev/community is asking for an LF account whereas the slack link on https://openssf.org/getinvolved/ let's folks create slack accounts in OpenSSF normally.

I have tried with an extra account I have and get an error trying to create an OpenSSF slack account as well: 

> mike@kusari.dev doesn’t have an account on this workspace.

I think we just need to update the link to: https://slack.openssf.org/ but I'm not sure.

**Comment by joshuagl** [comment]
Thanks, the Slack link has expired before. I don't think slack.openssf.org existed last time we ran into this but as that's the link from the main OpenSSF site to Slack we should use it too.

**Comment by MarkLodato** [comment]
I wish Slack allowed the invite link to redirect to a specific channel. Either we link directly to the channel, which only works for people who already have an account, or we link to the invite, which goes to `#general`. Really we want both: create an account, then go to a specific channel.

**Comment by kranurag7** [comment]
Hey there, 
I tried getting into the openssf slack because I wanted to get involved in #slsa-tooling but creating an account with Google is not working. I've a `@linux.com` email by LF and that's not working either. I tried all sorts of permutations and combinations and read some messages on Google Groups too about creating an account first and then try to log in, but it seems that's only possible if you've email from the domain listed below. 

<details><summary>Details</summary>
<p>

![image](https://github.com/slsa-framework/slsa/assets/81210977/a5048403-cc4a-4aed-8057-8da40967d5fb)


</p>
</details>
