### ISSUE TITLE
http/80 port is exposed on the slsa.dev site

### ISSUE THREAD

**Issue by aravindarc** [slsa-framework/slsa#542]
Is this intended or a mistake.

**Comment by MarkLodato** [comment]
slsa.dev is served by GitHub pages. We have no control over that. I assume they also serve plain http.

**Comment by 06kellyjac** [comment]
> You can enforce HTTPS for your GitHub Pages site to transparently redirect all HTTP requests to HTTPS.

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

@MarkLodato

**Comment by MarkLodato** [comment]
Yes, but is it needed? Modern browsers automatically switch to HTTPS when available. For example, if you type `http://slsa.dev` in Chrome, it automatically converts to `https://slsa.dev`. That option in GitHub Pages disallows anyone who tries to connect over HTTP using an older client. Is there really value in that?

**Comment by 06kellyjac** [comment]
I just posted to show it's possible. Whether it provides value I'll leave that to you.

No authed requests or anything in the path that needs hiding and isn't already obvious from the fact that someone is visiting slsa.dev

I'd say if someone is in a scenario where they can only access things via http they have other stuff to resolve before thinking about SLSA but yeah not really a value-add.

---

Although now that I think of it isnt the site netlify rather than GH pages.

**Comment by 06kellyjac** [comment]
I see.

Should probably drop the "powered by netlify" bit from the footer then
