### ISSUE TITLE
SLSA v1.0 RC feedback - Ephemeral and isolated

### ISSUE THREAD

**Issue by arewm** [slsa-framework/slsa#657]
> The build SHOULD NOT call out to remote execution unless it’s considered part of the “builder” within the trust boundary [[ref](https://slsa.dev/spec/v1.0-rc1/requirements#:~:text=The%20build%20SHOULD%20NOT%20call%20out%20to%20remote%20execution%20unless%20it%E2%80%99s%20considered%20part%20of%20the%20%E2%80%9Cbuilder%E2%80%9D%20within%20the%20trust%20boundary)]

Can this statement be clarified as it seems impossible to verify in its current form. Some possible points of confusion that result from this statement include:
* Would this prevent the vendoring of binary content as some process of the build was performed outside the trust boundary?
* Would this prevent `curl`ing pre-built artifacts to be used in a resulting artifact?
* Would leveraging something like NTP within the build be remote execution?
* Should this prevent pulling of untrusted container artifacts as well since this can also be a "building" process (i.e. https://github.com/imjasonh/kontain.me/tree/main/cmd/buildpack)?
* Since any remote access can potentially result in remote execution, should this be interpreted as a requirement for hermetic builds in complete network isolation?

Additionally, one component of isolation from other processes (and therefore reproducibility) is to _not_ use tag-based container pullspecs and instead use digest-pinned pullspecs. Since tags can change between build runs, it is possible that two builds can violate isolation if any tag-based references are used.

**Comment by arewm** [comment]
This comment seems related:

> The way we defined the core elements of a "secure" build service in the Secure Software Factory Ref Arch is pretty much as follows:
> * Secure orchestration of the build pipeline. i.e. only approved pipelines that follow established policy and rules should be allowed to run.
> * Secure orchestration of the build workload. i.e. only approved build workloads are allowed to be run, and if someone tampers with the orchestration of a workload it should be detected or prevented. An example here is using SPIFFE or other workload identities.
> * Secure the actions in the build workload itself. i.e. a build that tries to perform malicious actions should be prevented and the build workload should be isolated enough to limit blast radius. [[ref](https://github.com/slsa-framework/slsa/issues/599#issuecomment-1412319904:~:text=The%20way%20we,limit%20blast%20radius)]

Based on this interpretation by @mlieberman85, is the remote execution statement just trying to convey that only approved/trusted steps in the build process (i.e. Tekton Pipelines and Tasks) can be used? Even with this statement, it will be hard (if not impossible) to prove the lack of remote execution without requiring a restriction on remote access.

**Comment by mlieberman85** [comment]
Oops, missed this. Sorry about that.

So you're mostly accurate on the requirements. It is bad practice to pull from tags instead of digests. It's bad practice to have the build/compilation/packaging step pull down dependencies, it should happen before that, etc.

the tl;dr is - It's about restricting arbitrary execution to as small of a set of steps as possible, i.e. just the build/compilation of the artifact should have the ability to take source and dependencies and transform them into a binary artifact via compilation or other build process. In addition SLSA isn't transitive to its dependencies.

A couple of clarifications:
- SLSA is not transitive so if you include dependencies built outside the trust boundary that's fine. It just need to be in the materials section.
- This wouldn't prevent curling, just that the curling should happen to systems within the trust boundary OR that the untrusted curling happens outside. The risk being mitigated here is curl downloads something malicious, you run the build and it falsifies what it downloaded, so you don't have any proof of the evil binary you downloaded. If you follow the restrictions you might still be building against an evil binary but you have recorded in your SLSA attestation you downloaded that binary.
- NTP could be considered remote execution. There were some earlier discussions around using secure NTP in order to mitigate attacks against it. I'm not super familiar on what the status of that is. However if the NTP is running as a trusted service that would be considered along with the build service it's fine either way. Also if you use NTP outside the literal build action it falls under the same stuff as above.
- SLSA currently doesn't make any claims on the upstream dependencies. So pulling untrusted binaries is fine from a SLSA perspective. However, SLSA would record what untrusted binaries are downloaded. So in the example you listed you would get an untrusted dependency that was built by a separate build service that isn't SLSA compliant. Since SLSA isn't transitive it's ok. However, it might violate various organization's policies.
- We are pushing towards hermetic builds as potentially an L4 requirement in the future, but we believe this to be a less stringent requirement.

L3 will be difficult for a lot of folks. There are some common patterns out there for this. For example look at the CNCF supply chain security best practices guide (https://project.linuxfoundation.org/hubfs/CNCF_SSCP_v1.pdf) and the Secure Software Factory Reference Architecture (https://github.com/cncf/tag-security/blob/main/supply-chain-security/secure-software-factory/Secure_Software_Factory_Whitepaper.pdf) help in building an L3 build service.

**Comment by MarkLodato** [comment]
One comment that came up in chat is should we just say "Isolated"? The ephemeral environment is just one of several things you need to do to ensure that builds are isolated from one another. In fact, this is what an [early draft](https://github.com/slsa-framework/slsa/tree/v2021-04-21#proposed-slsa-definitions) did; we only added "ephemeral environment" later. I'm open to the change but would like to hear feedback from readers to see whether "ephemeral" is a plus or a minus.

**Comment by arewm** [comment]
I can work on a change to remove ephemeral from the requirements. Even if removed, it can still be included as a potential implementation detail. Instead of introducing two different types of build system isolation in addition to one build time isolation, we can try to simplify to one of each --

* `isolated`: A property of the build system that ensures any running build cannot interact with other builds (either currently or previously running) and that the build system is appropriately restricted from access outside the trusted boundary.
* `hermetic`: A property of a user's build event where the build can be performed without network access except that which is required by the build system.

Isolated is included in the v1.0 specification while hermetic is not.
