### ISSUE TITLE
Extension field format and periods

### ISSUE THREAD

**Issue by danzehme** [slsa-framework/slsa#670]
I am trying to make use of extension fields and the SLSA specification defers to the in-toto specification:

> Extension fields: Producers MAY add extension fields to any JSON object by using a property name that is a [TypeURI](https://github.com/in-toto/attestation/blob/main/spec/v1.0-draft/scalar_field_types.md#TypeURI). The use of URI is to protect against name collisions. Consumers MAY parse and use these extensions if desired. The presence or absence of the extension field MUST NOT influence the meaning of any other field, and the field MUST follow the monotonic princple.

This would mean that field names (not field values) would look like URLs.   I am storing my Provenances in MongoDB, but MongoDB does not allow periods in field names.  This is so that you can reference subdocuments with a period.    This means that I would have to restore to either mangling the extension field names before storing in the database.    I suspect this will be a problem with other databases and JSON tools.  The TypeURI seems like it was really meant for unique field values and not intended to create unique field names.   Please consider some other approach where the names do not have to include so many special characters (colon, period, and slash right now).

**Comment by TomHennen** [comment]
I wonder if the problem is that while in-toto Attestations changed guidance, the SLSA spec [still recommends URIs](https://slsa.dev/provenance/v1-rc1#:~:text=Producers%20MAY%20add%20extension%20fields%20using%20field%20names%20that%20are%20URIs.).  SLSA should probably update that guidance to be in-line with in-toto guidance?

**Comment by TomHennen** [comment]
I wonder if the problem is that while in-toto Attestations changed guidance, the SLSA spec [still recommends URIs](https://slsa.dev/provenance/v1-rc1#:~:text=Producers%20MAY%20add%20extension%20fields%20using%20field%20names%20that%20are%20URIs.).  SLSA should probably update that guidance to be in-line with in-toto guidance?

**Comment by marcelamelara** [comment]
Ah, I hadn't noticed, good catch. Yes, we should update this to match in-toto's guidance.

**Comment by danzehme** [comment]
> @danzehme I believe you opened issue [in-toto/attestation#147](https://github.com/in-toto/attestation/issues/147) for this. We have updated the extension fields guidelines on the in-toto side. Do the [new guidelines](https://github.com/in-toto/attestation/tree/main/spec/v1.0#parsing-rules) address your concerns/requirements?

Sorry I missed -- the new requires more than meet my needs.   Thanks for updating SLSA to reflect that.
