### ISSUE TITLE
"Verifying Artifacts": declare a preference for signing methodologies that rely on transparency logs

### ISSUE THREAD

**Issue by di** [slsa-framework/slsa#727]
>> If we do that, do you think that it would make sense for https://slsa.dev/spec/v1.0/verifying-artifacts to declare a preference for signing methodologies that rely on transparency logs?
>
> Yeah, that sounds like a good idea.

_Originally posted by @MarkLodato in https://github.com/slsa-framework/slsa/pull/673#discussion_r1146812053_

**Comment by joshuagl** [comment]
I'm curious whether folks still think this declaration of preference for TL dependent signing methodologies belongs in the _[verifying artifacts]_ page?

It probably doesn't belong in requirements, because it's not strictly required, but it feels like something that build platforms should be accounting for when designing [provenance generation](https://slsa.dev/spec/v1.0/requirements#provenance-generation). Another document aimed at build platforms is the [distributing provenance](https://slsa.dev/spec/v1.0/distributing-provenance) page, where this preference for TL based signing methodologies was originally included but didn't seem to fit.

My concern is that the [verifying artifacts] page is in the purview of consumers, not build platforms, and thus making recommendations about signature production in the place where we describe verification doesn't feel quite right.

Equally, if consensus is that [verifying artifacts] is the best place to put it, I'll make that change ASAP. We might mention it in the discussion of threat mitigation, specifically when discussing Threat E; or when discussing verification of the envelope's signature.

WDYT?

[verifying artifacts]: https://slsa.dev/spec/v1.0/verifying-artifacts

**Comment by joshuagl** [comment]
Another place we might mention this is the [How to SLSA for implementers](https://slsa.dev/how-to-infra) page under the [Build platform](https://slsa.dev/how-to-infra#build-platform) heading. 

However, given that section provides guided reading for build platform implementers and points to [Verifying build platforms](https://slsa.dev/spec/v1.0/verifying-systems), [Producing artifacts](https://slsa.dev/spec/v1.0/requirements), and [Provenance](https://slsa.dev/provenance/v1) pages of the spec I think we should add this to one of those pages.

I'm leaning toward just stating this preference in the [Authentic](https://slsa.dev/spec/v1.0/requirements#provenance-authentic) requirement as this is probably the main place where signing (as opposed to verifying) is discussed.

**Comment by arewm** [comment]
Why would the preference be for transparency logs instead of just timestamps? https://docs.sigstore.dev/cosign/timestamps/

I feel like it would make more sense for SLSA to have a preference for something abstract like a verifiable timestamp and then a community like Sigstore to have a more fine-grained preference (if at all).

**Comment by joshuagl** [comment]
Good question! Here's my understanding:

Transparency logs provide 1) observability. All signatures are published, so any compromised signatures can be detected and acted upon; 2) constraints on the signatures timestamp, which helps limit the impact of a key compromise (you don't need to invalidate all signatures, just those after the compromise).

If a producer cannot, or will not, make their signatures public, they can instead use a timestamp service to provide the latter property.

I believe both techniques (transparency logs and timestamps) provide useful, and complementary, security properties that are worth documenting.

**Comment by joshuagl** [comment]
Rekor/TL vs. a Timestamping service is covered in this post on the Sigstore blog (specifically, under the Rekor header): [Why you can’t use Sigstore without Sigstore](https://blog.sigstore.dev/why-you-cant-use-sigstore-without-sigstore-de1ed745f6fc/).

Some other useful references (more for myself than anyone reading the issue) to reference when documenting this:
- [Sigstore’s rekor, what is it and how does it work?](https://www.stacklok.com/post/sigstores-rekor-what-is-it-and-how-does-it-work)
- [Timestamps](https://docs.sigstore.dev/cosign/timestamps/) (Cosign docs)
- [Rekor Security Model](https://docs.sigstore.dev/security/#rekor-security-model) (Sigstore Security Model)
- [Sigstore: Software Signing For Everybody](https://dl.acm.org/doi/10.1145/3548606.3560596) (Sigstore paper) [announcement post](https://blog.sigstore.dev/sigstore-software-signing-for-everybody-has-been-published-in-the-proceedings-of-the-acm-bb7e7d679a73/)

**Comment by joshuagl** [comment]
I agree, signing mechanisms are nuanced and situational. Are you suggesting we don't make recommendations from within the formal specification, so that we don't appear to be prescribing something?

If so, and if the SLSA community feel strongly about recommending TL-based signing mechanisms, or at least using timestamping services (which this issue suggests), _where_ should we make that recommendation from? A blog post feels _too_ weak a statement of preference.

Perhaps in the [how to for infrastructure providers](https://slsa.dev/how-to-infra)?

**Comment by arewm** [comment]
Yes, I think that we shouldn't make a recommendation in the formal specification. 

In the end, though, a recommendation isn't a requirement, so if it does get included in the specification then it would still be a good starting point for build platforms. These platforms would then be able to make their own judgements about their implementations. It does give me pause to recommend a transparency log without context because of the potential issues around violating embargoes for users/organizations/platforms. This might not be an implementation detail that users of a platform would fully realize the effect of.

**Comment by joshuagl** [comment]
I tried adding something non-prescriptive in both how-to-infra and requirements and ended up submitting only the latter in #916.

The existing "how to infra" remarks are very high-level and this addition started to double the word count, making the suggestion feel out of place. I'd be happy to try again if folks think the how-to-infra page is the better candidate.
