### ISSUE TITLE
gitCommit: sha1 vs sha256

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa#797]
There's a new gitCommit in the specs https://github.com/slsa-framework/slsa/blob/379c7e1ec7c06656ccc689f7bfc6e7f800d66404/docs/provenance/schema/v1/provenance.cue#L36
sha1 is currently used, but GitHub have plans to introduce sha256 at some point.

Is the plan to differentiate them based on length or thru a prefix `shaxxx:value`?

**Comment by TomHennen** [comment]
When GitHub introduces sha256 will they be only generating sha256 or will they be generating both for a while?

My intuition is that most consumers of this value will only need to do equality comparison or pass it as a parameter and won't care if it's sha256 or sha1, but I have no data to back that up.

**Comment by adityasaky** [comment]
I don't know of GitHub's support for this but last I checked, there's a [4 stage transition plan in Git](https://git-scm.com/docs/hash-function-transition/2.40.0#_object_names_on_the_command_line) where phase 2 and 3 support both SHA-1 and SHA-256 hashes. I don't know if this thinking has changed elsewhere, perhaps on the ML, because this doc is quite old. I _believe_ on the in-toto side we can update our support for `git{Commit,Blob,Tree,Tag}` to indicate it could be SHA-1 or SHA-256. Differentiating by length should also suffice for now because a transition plan isn't active, if someone's using a SHA-256 Git repo, it has no interop with SHA-1 repos. When there is interop, we'll know how to identify object equivalence when presented with its SHA-1 and SHA-256 hashes.

**Comment by MarkLodato** [comment]
Let's close this in favor of in-toto/attestation#184
