### ISSUE TITLE
Contributor merge etiquette could be defined in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by abacchi** [slsa-framework/slsa#821]
@MarkLodato and I were chatting earlier about how it would be nice for us to define the etiquette for merging PRs.

To my knowledge we don't have anything clearly written out - I am hoping we can take notes from other OSS projects that have this defined. 

Who should be the one to hit the "Merge pull request" button once approval is provided? The author?
We talked about how even though he had approved the PR- maybe we should wait a day for others to comment and approve before merging it, which I think is very fair.

- Mark had recommended we create some sort of GitHub actions configuration to enforce our convention once its decided.

**Comment by lehors** [comment]
I think it is a good idea to document how we work. There is more than when to merge though. For instance, some projects favor squashing commits on merge, rebasing over merging main. I've tried to mimic what I was seeing others do but it would be better to document our practices so we can have consistency and no guessing work.

When it comes to merging I think we have to acknowledge that different situations call for different protocols. If the PR is merely fixing a typo or similar I don't think we need to wait.

**Comment by MarkLodato** [comment]
Going forward, I would like to be a bit more rigorous about this. What do you think about the following?

- Always squash+merge (unless otherwise requested)
- Meaningful commit titles and messages (the PR for squash+merge, or individual commits if merge or rebase)
- Categorize each PR to indicate the type of change (see below), perhaps as a PR title prefix ("style: add spacing ...")
- Wait to merge until X hours after the last comment, depending on category (aka "lazy consensus")
- Number of required approvers depends on category
  - Author implicitly grants own approval (if they can)
  - If multiple approvers are required, they must represent different organizations
  - (We should figure out a better story for who is allowed to grant approval.)
- Tooling (GitHub Action?) enforces the above, when possible

Potential categories (choose the highest one):

| Tag | Description | Wait | Approvers |
| --- | --- | --- | --- |
| `spec` | includes a change to the meaning of the specification | 72h? | 3? |
| `editorial` | clarifies the specification without changing meaning, or changes a non-specification page | 24h? | 2? |
| `style` | user-visible style or layout change but no content change | none? | 1? |
| `impl` | user-invisible change, such as editing a README or the build rules | none | 1 |

**Comment by joshuagl** [comment]
I'm all for the improved rigor. I think we should be able to use a combination of branch protection and GHA to achieve something like this. I've seen several projects enforcing [convential commits](https://www.conventionalcommits.org/en/v1.0.0/) with a GHA like [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request).

**Comment by MarkLodato** [comment]
Oh cool, I've never seen conventional commits before! Thanks for the link! Do you think we'd use that as-is? "fix" vs "feat" is a bit awkward for a specification rather than software.

**Comment by joshuagl** [comment]
I agree that the conventional commits don't quite match. I think we'd only use conventional commits as-is if we do not have folks willing and able to do the work on creating and maintaining tooling. 

Let's figure out how much effort it is to use our own tags before we decide?

**Comment by kpk47** [comment]
I mailed #890 to update CONTRIBUTORS.md and enable a lint check for commit tags. Enforcing the number of approvals and waiting period will be harder. 

AFAICT, GitHub only supports requirements for multiple approvals at the branch level. Our repo isn't set up for having separate branches at the moment, but that may change if/when https://github.com/slsa-framework/slsa-proposals/tree/main/0006 is implemented. We may be able to meet our multi-party approval goals by setting different review thresholds for each branch, though we wouldn't be able to set a different threshold for each tag.

I think we can enforce the waiting period with a custom scheduled action. We'd need to call the GitHub API to list out all the open PRs, check the github.event.review.state field [0], and then merge PRs whose approval event was long enough ago in the past. Assuming we run the job daily, we'll merge PRs at most one day after the waiting period passes.

[0] https://github.com/orgs/community/discussions/25372

**Comment by lehors** [comment]
For what it's worth, I think defining our policy and publishing it so that everybody knows what to expect and what to do will already go a long way. If some of it can easily be enforced with some simple settings on github let's do that but let's not over engineer it and end up just adding to our technical debt.

**Comment by kpk47** [comment]
+1 -- I think having a written policy and asking maintainers to handle merging is the best solution.

Unless anyone objects, I'll close out this issue when merging #890.
