### ISSUE TITLE
SLSA 1.0-rc2 feedback: Drop base64 encoding requirement from ResourceDescriptor.contents?

### ISSUE THREAD

**Issue by wlynch** [slsa-framework/slsa#834]
Minor piece of feedback / question:

ResourceDescriptor.contents is currently described as: 

> base64-encoded bytes, optional

I think it's reasonable to enforce character class constraints on this field, but do we need to go as far as to say this should always be base64 encoded? I'm thinking about simple key/value pairs contained in `byproducts` that would use ASCII encoding - requiring base64 around these may be unnecessary. 🤔 

The description also says:

> The semantics are up to the producer and consumer. The uri or mediaType MAY be used by the producer as hints for how consumers should parse content.

RFC 6838 already has a section for encoding requirements: https://www.rfc-editor.org/rfc/rfc6838.html#section-4.8. Perhaps this is enough to inform to clients what the encoding expectations are for this field?

**Comment by wlynch** [comment]
Or is the right way to read this "contents need to be base64-compatible" - e.g. if the value itself is a valid base64 string, that's okay?

**Comment by MarkLodato** [comment]
Sorry, this is actually an issue for the more general in-toto/attesation project. Would you mind copying your issue there? Thanks!

https://github.com/in-toto/attestation/issues/new

(I have an answer but would like to keep the history in one place. I'd create the issue for you, but then my name would be attached to it instead of yours.)

**Comment by wlynch** [comment]
Done! https://github.com/in-toto/attestation/issues/188

**Comment by MarkLodato** [comment]
Thanks!
